apiVersion: v1
kind: Service
metadata:
  name: hello-world-node-service
spec:
  type: NodePort
  selector:
    app: hello-world-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
